/*
  opengrid_inbox.scad

  A wall-mounted paper / envelope / file inbox that hangs on an openGrid wall
  via openConnect slots cut into its back panel.

  The pocket is a wedge: a full-height back panel against the wall, a shorter
  front panel raked outward so sheets lean back and stay visible, closed at the
  sides by tapering panels, with a finger cutout in the front edge so a stack
  can be grabbed.

  ---------------------------------------------------------------------------
  Licensing

  The pocket geometry in this file is original work by zing3d-labs and is
  licensed under the repository license, CC BY-NC-SA 4.0 (see ../../LICENSE).

  The openConnect mount is generated by mitufy's connector library
  (external/opengrid-projects/lib/openconnect_lib.scad), which is licensed
  Creative Commons Attribution 4.0 International:

      openConnect / openGrid connector libraries
      Created by mitufy - https://github.com/mitufy
      https://www.printables.com/model/1559478-openconnect-opengrids-own-connector-system

  openGrid is created by David D:
      https://www.printables.com/model/1214361-opengrid-walldesk-mounting-framework-and-ecosystem

  This file deliberately depends on the CONNECTOR LIBRARY ONLY. mitufy's
  holder / drawer / shelf / hook / label / gadget generators are CC BY-SA 4.0;
  deriving from one of those would impose ShareAlike terms that conflict with
  this repository's CC BY-NC-SA 4.0 license. Do not reintroduce such a
  dependency here.
  ---------------------------------------------------------------------------
*/

// Brings in BOSL2 (via lib/opengrid_base.scad) along with the openConnect
// slot modules and the OG_/OC_ constants, so no separate BOSL2 include.
include <../../external/opengrid-projects/lib/openconnect_lib.scad>

/* [Paper] */

// Sheet size the pocket is built around. Drives the interior width, and the
// panel heights via the percentages below.
Paper_Size = "US Letter"; // [A4, US Letter, A5, Custom]

// Which way the sheet sits in the pocket. Landscape swaps the two dimensions.
Paper_Orientation = "Portrait"; // [Portrait, Landscape]

// Sheet width in mm, used when Paper_Size is Custom. Give the portrait
// dimensions; Paper_Orientation swaps them.
Custom_Paper_Width = 215.9;

// Sheet height in mm, used when Paper_Size is Custom
Custom_Paper_Height = 279.4;

// Extra interior width beyond the sheet, total across both sides, so sheets
// drop in freely. With Snap_Width_To_Grid on this is only a lower bound - the
// snap rounds up to a whole tile and the surplus becomes clearance. Watch the
// echoed clearance figure: raising this past a tile boundary adds a full 28mm
// of width. The default is 3 because it keeps portrait US Letter on 8 tiles.
Paper_Clearance = 3; // [0:0.5:20]

/* [Pocket Shape] */

// Interior depth of the pocket at the floor - the paper stack capacity, in mm
Pocket_Depth = 25; // [5:1:80]

// Outward rake of the front panel, measured from vertical, in degrees
Rake_Angle = 12; // [0:1:35]

// Height of the back panel, as a percentage of the sheet height. Snapped to
// whole tiles unless Snap_Height_To_Grid is off.
Back_Height_Percent = 50; // [15:1:100]

// Height of the front panel, as a percentage of the sheet height. Must be
// enough below Back_Height_Percent for the side panels to taper.
Front_Height_Percent = 30; // [5:1:95]

// How to refine the front and side panel corners
Corner_Refinement_Type = "Fillet"; // [None, Chamfer, Fillet]

// Measurement for the selected corner refinement, in mm. Automatically reduced
// at any corner too tight to take it.
Corner_Refinement_Size = 3; // [0:0.5:15]

/* [Thickness] */

// Thickness of the front and side panels, in mm
Wall_Thickness = 2.4; // [1.2:0.2:6]

// Thickness of the back panel - must be thick enough to contain the openConnect slots
Back_Thickness = 4; // [3.5:0.1:10]

// Thickness of the pocket floor, in mm
Floor_Thickness = 2.4; // [1.2:0.2:6]

/* [Finger Cutout] */

// Shape of the grab cutout in the top edge of the front panel
Finger_Cutout_Style = "Scallop"; // [Scallop, Notch, None]

// Width of the cutout, in mm
Finger_Cutout_Width = 70; // [10:1:250]

// How far the cutout reaches down from the front panel top edge, in mm
Finger_Cutout_Depth = 22; // [2:1:100]

/* [openConnect Mount] */

// Round the outer width UP to a whole 28mm tile, so the slot grid reaches the
// side edges instead of leaving a partial tile unused. Rounding up rather than
// to nearest keeps the pocket from ever pinching the sheet; the added width
// becomes extra paper clearance.
Snap_Width_To_Grid = true;

// Round the back panel height to the nearest whole 28mm tile, so the slot grid
// reaches the top and bottom edges.
Snap_Height_To_Grid = true;

// Slot columns across the back panel. 0 fits as many as the width allows.
Mount_Horizontal_Grids = 0; // [0:1:20]

// Slot rows up the back panel. 0 fits as many as the height allows.
Mount_Vertical_Grids = 0; // [0:1:20]

// Where the slot grid sits when the back panel is not a whole number of tiles tall
Mount_Vertical_Alignment = "Center"; // [Center, Top, Bottom]

// Which grid positions get a slot
Slot_Position = "All"; // [All, Staggered, Edge Rows, Edge Columns, Corners]

// Which slots get the locking nub. More locks means a tighter fit and a harder install.
Slot_Lock_Distribution = "Corners"; // [All, Staggered, Corners, Top Corners, Bottom Corners, None]

// Side the locking nubs sit on, as seen from the wall side of the back panel
Slot_Lock_Side = "Left"; // [Left, Right]

// Flip the slot entry ramp. Useful when printing the back panel on its side.
Slot_Entry_Ramp_Flip = false;

/* [Misc] */

// Value of $fn for curves on the design
Smoothing = 64; // [16:8:256]

/* [Hidden] */

// Shrinks each requested corner radius until its roundover fits the two edges
// meeting at that corner, so no combination of Customizer values can produce a
// path BOSL2 refuses to round. A roundover of radius r at a corner whose
// interior angle is a consumes r * tan((180 - a) / 2) of each adjacent edge;
// holding that to just under half the edge guarantees two neighbouring
// roundovers never overlap, with enough slack that an exactly-tight fit does
// not trip BOSL2's floating-point check.
CORNER_FIT_MARGIN = 0.99;

// Corner refinement is additionally capped at CORNER_CAP_BASE plus this
// multiple of the front panel's slab run - see refinement_cap below for why,
// and for the measurements these two numbers are fitted to.
CORNER_CAP_BASE = 2;
CORNER_CAP_SLAB_MULTIPLE = 0.8;

function cornerConsumptionRate(path, i) =
  let(n = len(path))
    tan((180 - vector_angle(path[(i - 1 + n) % n], path[i], path[(i + 1) % n])) / 2);

function fitCornerRadii(path, radii) =
  let(
    n = len(path),
    segments = [for (i = [0:n - 1]) norm(path[(i + 1) % n] - path[i])]
  ) [
    for (i = [0:n - 1])
      let(
        consumedPerRadius = cornerConsumptionRate(path, i),
        shortestEdge = min(segments[(i - 1 + n) % n], segments[i])
      ) radii[i] <= 0 || consumedPerRadius <= 0
        ? 0
        : min(radii[i], CORNER_FIT_MARGIN * shortestEdge / 2 / consumedPerRadius)
  ];

// BOSL2 takes a radius for circular roundovers but a joint distance for
// chamfers. A chamfer that meets its edges where a radius-r roundover would be
// tangent has joint = r * tan((180 - a) / 2) - the same edge length the fitter
// above budgets for - so a fitted radius converts straight across and both
// refinements are guaranteed to fit identically.
function cornerJoints(path, radii) =
  [for (i = [0:len(path) - 1]) radii[i] * cornerConsumptionRate(path, i)];

// Paper presets in mm, [width, height].
A4_SIZE = [210, 297];
US_LETTER_SIZE = [215.9, 279.4];
A5_SIZE = [148, 210];

// Solid material kept behind the deepest point of an openConnect slot.
MIN_BACK_WALL = 0.8;

// Presets are stated portrait; Landscape swaps them.
_portraitSize =
  Paper_Size == "A4" ? A4_SIZE
  : Paper_Size == "US Letter" ? US_LETTER_SIZE
  : Paper_Size == "A5" ? A5_SIZE
  : [Custom_Paper_Width, Custom_Paper_Height];

_paperSize = Paper_Orientation == "Landscape"
  ? [_portraitSize.y, _portraitSize.x]
  : _portraitSize;

openGridInbox(
  paperWidth=_paperSize.x,
  paperHeight=_paperSize.y,
  paperClearance=Paper_Clearance,
  pocketDepth=Pocket_Depth,
  rakeAngle=Rake_Angle,
  backHeightPercent=Back_Height_Percent,
  frontHeightPercent=Front_Height_Percent,
  cornerRefinementType=Corner_Refinement_Type,
  cornerRefinementSize=Corner_Refinement_Size,
  wallThickness=Wall_Thickness,
  backThickness=Back_Thickness,
  floorThickness=Floor_Thickness,
  fingerCutoutStyle=Finger_Cutout_Style,
  fingerCutoutWidth=Finger_Cutout_Width,
  fingerCutoutDepth=Finger_Cutout_Depth,
  snapWidthToGrid=Snap_Width_To_Grid,
  snapHeightToGrid=Snap_Height_To_Grid,
  mountHorizontalGrids=Mount_Horizontal_Grids,
  mountVerticalGrids=Mount_Vertical_Grids,
  mountVerticalAlignment=Mount_Vertical_Alignment,
  slotPosition=Slot_Position,
  slotLockDistribution=Slot_Lock_Distribution,
  slotLockSide=Slot_Lock_Side,
  slotEntryRampFlip=Slot_Entry_Ramp_Flip
);

// Wall-mounted paper inbox, mounted to openGrid by openConnect slots cut into
// the back panel.
//
// Orientation is as-mounted: +Y points at the wall, so the back panel face
// lies in the plane Y = 0 and the pocket hangs out toward -Y. +Z is up.
//
// Panel geometry is kept in one submodule per panel (backPanel, floorPanel,
// frontPanel, sidePanels) so a later perforation pass can mask individual
// faces without restructuring the assembly. The mount is likewise isolated in
// mountSlots(), so an alternative mounting system can be added alongside it
// without touching the pocket.
module openGridInbox(
  paperWidth = 215.9,
  paperHeight = 279.4,
  paperClearance = 4,
  pocketDepth = 25,
  rakeAngle = 12,
  backHeightPercent = 50,
  frontHeightPercent = 30,
  cornerRefinementType = "Fillet",
  cornerRefinementSize = 3,
  wallThickness = 2.4,
  backThickness = 4,
  floorThickness = 2.4,
  fingerCutoutStyle = "Scallop",
  fingerCutoutWidth = 70,
  fingerCutoutDepth = 22,
  snapWidthToGrid = true,
  snapHeightToGrid = true,
  mountHorizontalGrids = 0,
  mountVerticalGrids = 0,
  mountVerticalAlignment = "Center",
  slotPosition = "All",
  slotLockDistribution = "Corners",
  slotLockSide = "Left",
  slotEntryRampFlip = false,
  anchor, orient, spin
) {
  $fn = Smoothing;

  slotHeight = struct_val(ocslot_cfg(), "total_height");

  // Snapping lands the panel on whole tiles so the slot grid reaches its edges
  // with nothing left over. Width rounds UP - rounding down would eat into the
  // paper clearance and could pinch the sheet - so any added width becomes
  // extra clearance. Height rounds to nearest, since nothing constrains it.
  natural_outer_width = paperWidth + paperClearance + 2 * wallThickness;
  outer_width = snapWidthToGrid
    ? OG_TILE_SIZE * max(1, ceil(natural_outer_width / OG_TILE_SIZE))
    : natural_outer_width;
  interior_width = outer_width - 2 * wallThickness;

  natural_back_height = paperHeight * backHeightPercent / 100;
  backHeight = snapHeightToGrid
    ? OG_TILE_SIZE * max(1, round(natural_back_height / OG_TILE_SIZE))
    : natural_back_height;
  frontHeight = paperHeight * frontHeightPercent / 100;

  // Depths are measured forward from the wall plane, and are all positive.
  // The minus sign is applied at the call site, since the model occupies -Y.
  front_slab_run = wallThickness / cos(rakeAngle);
  front_inner_bottom_depth = backThickness + pocketDepth;
  front_outer_bottom_depth = front_inner_bottom_depth + front_slab_run;
  front_inner_top_depth = front_inner_bottom_depth + frontHeight * tan(rakeAngle);
  front_outer_top_depth = front_inner_top_depth + front_slab_run;
  total_depth = front_outer_top_depth;

  // The side panels and the front panel share the front-top corner but cannot
  // refine it equally: the front panel's top face is only front_slab_run wide,
  // so its own corner gets clamped to a fraction of a millimetre while the side
  // panels would take the full size. Past a point the side panels refine back
  // further than that narrow top face can bridge and a notch opens through to
  // the pocket at each front corner - a valid solid, but two unintended holes.
  //
  // The onset grows with front_slab_run but not proportionally, so this cap is
  // affine. It is fitted below the measured first failure for a chamfer, which
  // cuts more than the equivalent fillet and so fails earliest:
  //     slab 1.23mm - safe at 4, notched at 6   -> cap 2.98
  //     slab 2.45mm - safe at 6, notched at 8   -> cap 3.96
  //     slab 6.13mm - safe at 8, notched at 15  -> cap 6.90
  // Re-measure if the front panel or side silhouette changes shape.
  refinement_cap = CORNER_CAP_BASE + CORNER_CAP_SLAB_MULTIPLE * front_slab_run;
  corner_size = cornerRefinementType == "None" ? 0 : min(cornerRefinementSize, refinement_cap);

  assert(backHeight > frontHeight + corner_size,
    str("Back_Height_Percent must exceed Front_Height_Percent by enough to clear Corner_Refinement_Size (",
      corner_size, "mm on a ", paperHeight, "mm sheet is ",
      100 * corner_size / paperHeight, "%), so the side panels can taper."));
  assert(backThickness >= slotHeight + MIN_BACK_WALL,
    str("Back_Thickness must be at least ", slotHeight + MIN_BACK_WALL,
      "mm to contain the openConnect slots plus a solid backing wall."));
  assert(pocketDepth > 2 * wallThickness,
    "Pocket_Depth must leave room for the panel walls; increase it or thin the walls.");
  assert(fingerCutoutStyle == "None" || fingerCutoutWidth < interior_width,
    "Finger_Cutout_Width must be narrower than the pocket interior.");
  assert(fingerCutoutStyle == "None" || fingerCutoutDepth < frontHeight - floorThickness,
    "Finger_Cutout_Depth must not reach the pocket floor.");

  // Slot grid, sized to whatever whole tiles fit unless overridden.
  h_grids = mountHorizontalGrids > 0 ? mountHorizontalGrids : floor(outer_width / OG_TILE_SIZE);
  v_grids = mountVerticalGrids > 0 ? mountVerticalGrids : floor(backHeight / OG_TILE_SIZE);
  assert(h_grids >= 1 && v_grids >= 1,
    "The back panel is too small for a single openConnect tile (28mm); enlarge the paper size or Back_Height_Percent.");

  echo(str(
    "opengrid_inbox: ", outer_width, " x ", total_depth, " x ", backHeight, "mm outer, ",
    "front panel ", frontHeight, "mm, ",
    h_grids, "x", v_grids, " openConnect tiles leaving ",
    outer_width - h_grids * OG_TILE_SIZE, "mm width and ",
    backHeight - v_grids * OG_TILE_SIZE, "mm height unused by the grid. ",
    "Sheet ", paperWidth, " x ", paperHeight, "mm sits in a ", interior_width,
    "mm pocket (", interior_width - paperWidth, "mm clearance) with ",
    paperHeight - frontHeight, "mm visible above the front panel."
  ));

  if (cornerRefinementType != "None" && cornerRefinementSize > refinement_cap)
    echo(str(
      "opengrid_inbox: corner refinement reduced from ", cornerRefinementSize, "mm to ",
      refinement_cap, "mm - a ", wallThickness,
      "mm front panel cannot bridge more than that without opening a notch at the front corners. ",
      "Thicken Wall_Thickness to allow a larger one."
    ));

  grid_height = v_grids * OG_TILE_SIZE;
  grid_center_z =
    mountVerticalAlignment == "Top" ? backHeight - grid_height / 2
    : mountVerticalAlignment == "Bottom" ? grid_height / 2
    : backHeight / 2;

  // Silhouette of one side panel, seen from the side, as [y, z] pairs.
  side_profile = [
    [0, 0],
    [-front_outer_bottom_depth, 0],
    [-front_outer_top_depth, frontHeight],
    [-backThickness, backHeight],
    [0, backHeight],
  ];
  side_radii = [0, corner_size, corner_size, corner_size, 0];

  // Raked front panel, seen from the side, as [y, z] pairs.
  front_profile = [
    [-front_inner_bottom_depth, 0],
    [-front_outer_bottom_depth, 0],
    [-front_outer_top_depth, frontHeight],
    [-front_inner_top_depth, frontHeight],
  ];
  front_radii = [0, 0, corner_size, corner_size];

  // Extrudes a [y, z] profile along X, centered on the origin, refining its
  // corners first. Chamfers are specified by joint distance rather than radius,
  // so a fitted radius is converted; both consume the same edge length.
  module extrudeProfile(profile, radii, width) {
    fitted = fitCornerRadii(profile, radii);
    refined =
      max(fitted) <= 0 ? profile
      : cornerRefinementType == "Chamfer"
        ? round_corners(profile, joint=cornerJoints(profile, fitted), method="chamfer", closed=true)
        : round_corners(profile, radius=fitted, method="circle", closed=true);
    rotate([90, 0, 90])
      linear_extrude(height=width, center=true)
        polygon(refined);
  }

  module backPanel() {
    fwd(backThickness / 2) up(backHeight / 2)
      cuboid([outer_width, backThickness, backHeight]);
  }

  module floorPanel() {
    floor_depth = front_outer_bottom_depth - backThickness;
    fwd(backThickness + floor_depth / 2) up(floorThickness / 2)
      cuboid([outer_width, floor_depth, floorThickness]);
  }

  module frontPanel() {
    extrudeProfile(front_profile, front_radii, outer_width);
  }

  module sidePanels() {
    xcopies(spacing=outer_width - wallThickness, n=2)
      extrudeProfile(side_profile, side_radii, wallThickness);
  }

  // Grab cutout in the top edge of the front panel. Extruded along Y so the
  // shape reads true from the front despite the rake, and bounded in Y so it
  // never reaches the back panel.
  module fingerCutout() {
    cut_length = total_depth - front_inner_bottom_depth + 2;
    cut_center_depth = front_inner_bottom_depth + cut_length / 2 - 1;

    if (fingerCutoutStyle == "Scallop") {
      // Radius of the circle whose chord is the cutout width at the cutout depth.
      scallop_radius = fingerCutoutDepth / 2 + pow(fingerCutoutWidth, 2) / (8 * fingerCutoutDepth);
      fwd(cut_center_depth) up(frontHeight - fingerCutoutDepth + scallop_radius)
        xrot(90) cyl(r=scallop_radius, h=cut_length);
    } else if (fingerCutoutStyle == "Notch") {
      notch_rounding = min(fingerCutoutWidth / 4, fingerCutoutDepth / 2);
      fwd(cut_center_depth) up(frontHeight + fingerCutoutDepth)
        cuboid(
          [fingerCutoutWidth, cut_length, 2 * fingerCutoutDepth],
          rounding=notch_rounding,
          edges=[BOTTOM + LEFT, BOTTOM + RIGHT],
          anchor=TOP
        );
    }
  }

  // openConnect slots, cut into the wall-facing side of the back panel.
  // The library builds a grid in its own frame (+Y up the wall, +Z into the
  // panel), so xrot(90) lands it on the Y = 0 wall plane facing outward.
  module mountSlots() {
    up(grid_center_z) xrot(90)
      openconnect_slot_grid(
        slot_type="slot",
        horizontal_grids=h_grids,
        vertical_grids=v_grids,
        slot_slide_direction="Up",
        slot_position=slotPosition,
        slot_lock_distribution=slotLockDistribution,
        slot_lock_side=slotLockSide,
        slot_entryramp_flip=slotEntryRampFlip,
        excess_thickness=EPS
      );
  }

  named_anchors = [
    named_anchor("wall", [0, total_depth / 2, 0], BACK, 0),
    named_anchor("back_top", [0, total_depth / 2 - backThickness / 2, backHeight / 2], UP, 0),
    named_anchor("pocket_floor",
      [0, total_depth / 2 - (backThickness + pocketDepth / 2), floorThickness - backHeight / 2], UP, 0),
    named_anchor("front_top",
      [0, total_depth / 2 - (front_inner_top_depth + front_slab_run / 2), frontHeight - backHeight / 2], UP, 0),
  ];

  attachable(
    size=[outer_width, total_depth, backHeight],
    anchors=named_anchors,
    anchor=anchor, orient=orient, spin=spin
  ) {
    back(total_depth / 2) down(backHeight / 2)
      difference() {
        union() {
          backPanel();
          floorPanel();
          frontPanel();
          sidePanels();
        }
        fingerCutout();
        mountSlots();
      }
    children();
  }
}
