/*
  opengrid_cupholder.scad

  A cup holder that mounts to an openGrid board through a flat base, with
  optional handle slots cut through the wall so mugs with handles can sit in it.

  Two mounts are offered, and they are alternatives rather than additions:

    openConnect - the base is a plain slab with openConnect slots cut into the
                  face that meets the board. Screw openConnect connectors into
                  the board first, then slide the holder onto them. The default.
    Snaps       - openGrid snaps stand proud of the base and click into the
                  tiles. The original mount.

  The model stands the way it is used: the base sits on the Z = 0 plane with
  its board-facing side down, and the cup opens upward above it.

  Only one of the two is ever built. Both claim the same tiles from the same
  face of the base, and the snaps stand off exactly the face the openConnect
  mount needs flat against the board, so a holder carrying both could not sit
  down on the board at all.

  ---------------------------------------------------------------------------
  Directions

  Two things in this file point somewhere: the handle slots take an angle, and
  the openConnect mount takes compass-style direction names. They share one
  frame, so a slot can be lined up with the mount by number rather than by eye:

      +X    angle   0    Slot_Slide_Direction "Right"
      +Y    angle  90    Slot_Slide_Direction "Up"
      -X    angle 180    Slot_Slide_Direction "Left"
      -Y    angle 270    Slot_Slide_Direction "Down"

  The angle is measured looking down into the cup, counterclockwise from +X,
  the way zrot() measures - so 0 is to the right, 90 away from you, 180 to the
  left, 270 toward you. Both mounts read it the same way, so changing
  Mount_Type leaves the slots where they are.

  The four direction names come from mitufy's connector library. They are
  written above as the axes they actually land on rather than as left and right
  from some viewpoint, because the cup and the underside it mounts by are
  looked at from opposite sides and naming one of them would settle less than
  it appears to.

  ---------------------------------------------------------------------------
  Licensing

  The cup holder geometry in this file is original work by zing3d-labs and is
  licensed under the repository license, CC BY-NC-SA 4.0 (see ../../LICENSE).

  The openConnect mount is generated by mitufy's connector library
  (external/opengrid-projects/lib/openconnect_lib.scad), which is licensed
  Creative Commons Attribution 4.0 International:

      openConnect / openGrid connector libraries
      Created by mitufy - https://github.com/mitufy
      https://www.printables.com/model/1559478-openconnect-opengrids-own-connector-system

  openGrid is created by David D:
      https://www.printables.com/model/1214361-opengrid-walldesk-mounting-framework-and-ecosystem

  The snap mount comes from QuackWorks (external/QuackWorks), by way of
  opengrid_facade.scad. QuackWorks is CC BY-NC-SA 4.0, the same license this
  repository uses, so that dependency carries no additional terms.

  This file deliberately depends on the CONNECTOR LIBRARY ONLY. mitufy's
  holder / drawer / shelf / hook / label / gadget generators are CC BY-SA 4.0;
  deriving from one of those would impose ShareAlike terms that conflict with
  this repository's CC BY-NC-SA 4.0 license. Do not reintroduce such a
  dependency here.
  ---------------------------------------------------------------------------
*/

// Brings in BOSL2 (via lib/opengrid_base.scad) along with the openConnect
// slot modules and the OG_/OC_ constants, so no separate BOSL2 include.
include <../../external/opengrid-projects/lib/openconnect_lib.scad>
use <opengrid_facade.scad>

/* [Cup Holder] */

// Inner diameter at the cup opening (top), in mm
Cup_Holder_Top_Diameter = 90;

// Inner diameter at the facade (mounting) end, in mm
Cup_Holder_Bottom_Diameter = 75;

// Height of the cup holder body, in mm
Cup_Holder_Height = 90;

// Thickness of the cup holder walls, in mm
Wall_Thickness = 2;

/* [Handle Slots] */

// Number of slots cut through the cup wall so mugs with handles can sit in the
// holder, spaced evenly around the circumference. 0 leaves the wall solid.
Handle_Slot_Count = 0; // [0:1:8]

// How far each slot reaches down from the cup opening (the wide top rim), in mm
Handle_Slot_Height = 45; // [1:1:200]

// Width of the slot, in mm. Sized to the handle that has to pass through it,
// so it is a flat measurement rather than a share of the circumference.
Handle_Slot_Width = 30; // [1:0.5:120]

// Angle of the first slot around the cup, in degrees. The remaining slots
// follow evenly around from it. Measured looking down into the cup from above,
// counterclockwise from +X, the way zrot() measures:
//
//     0 = right,  90 = back (away from you),  180 = left,  270 = front
//
// Both mounts read it the same way, so changing Mount_Type does not move the
// slots.
Handle_Slot_Start_Angle = 0; // [0:5:355]

// How to break the two ends of each slot - the mouth at the rim and the closed
// inner end
Handle_Slot_End_Refinement_Type = "Fillet"; // [None, Chamfer, Fillet]

// Measurement for the selected refinement - fillet radius or chamfer leg, in mm
Handle_Slot_End_Refinement_Size = 10; // [0.5:0.5:20]

/* [Base Settings] */

// How the base attaches to the board. openConnect slides onto connectors
// screwed into the tiles; snaps click into the tiles directly. The two are
// alternatives - the options below apply only to the mount selected here.
Mount_Type = "openConnect"; // [openConnect, Snaps]

// Thickness of the mounting base, in mm. This is also the floor of the cup.
// Left open rather than ranged: the snap mount is happy with a thin base, and
// the openConnect mount asserts its own minimum of 2.7mm of slot plus 0.8mm of
// solid floor beneath it, so it says so itself rather than the slider hiding it.
Base_Thickness = 4;

// Use the bottom (open end) diameter to size the grid instead of the top diameter.
// The top diameter may overlap additional tiles slightly, which is fine if enabled.
Size_Base_Units_To_Bottom_Diameter = false;

// How to adjust corners for visual appeal
Corner_Refinement_Type = "Fillet"; // [None, Chamfer, Fillet]

// Measurement for the selected corner refinement
Corner_Refinement_Size = 5; // [2:0.5:20]

/* [Snap Mount] */

// Version of the tile, Full (6.8mm) or Lite (3.4mm)
Grid_Type = "Lite"; // [Full,Lite]

// Snap Placement
Snap_Placement = "Corners"; // [All, Edges, Corners]

/* [openConnect Mount] */

// Direction the holder slides to come off the connectors, in the model's own
// axes: "Right" is +X, "Left" is -X, "Up" is +Y, "Down" is -Y. Those are the
// axes Handle_Slot_Start_Angle is measured in, so "Right" is that angle's 0,
// "Up" its 90, "Left" its 180 and "Down" its 270. The holder seats by sliding
// the opposite way, so point this at whichever side of the board has room to
// work. On a horizontal board none of the four is uphill.
Slot_Slide_Direction = "Up"; // [Up, Down, Left, Right]

// Which grid positions get a slot. A slot costs nothing to print, so cutting
// all of them keeps every board position usable; the connectors you actually
// screw into the board are still up to you.
Slot_Position = "All"; // [All, Staggered, Edge Rows, Edge Columns, Corners]

// Which slots get the locking nub - the detent that stops the holder sliding
// back off. All, because you pick which handful of tiles to put connectors in,
// and the slots you happen to pick should be the locking ones. Nothing else
// holds the holder on a horizontal board, so None is not advisable here. Thin
// this out only if the fit comes out too tight to seat by hand.
Slot_Lock_Distribution = "All"; // [All, Staggered, Corners, Top Corners, Bottom Corners, None]

// Side of the slot the locking nubs sit on. The slot turns with
// Slot_Slide_Direction and this side turns with it, so it is worth naming the
// axes: with a slide of "Up" or "Down", "Left" puts the nubs on the -X side
// and "Right" on the +X side; with a slide of "Left" or "Right", "Left" puts
// them on the -Y side and "Right" on the +Y side.
Slot_Lock_Side = "Left"; // [Left, Right]

// Flip the slot entry ramp, which changes which way its overhangs face
Slot_Entry_Ramp_Flip = false;

/* [Misc] */

// Value of $fn for curves on the design
Smoothing = 150; // [10:10:300]

/* [Hidden] */

// Solid material kept under the deepest point of an openConnect slot, so the
// cup keeps a continuous floor.
MIN_BASE_WALL = 0.8;

openGridCupholder(
  cupHolderBottomDiameter=Cup_Holder_Bottom_Diameter,
  cupHolderTopDiameter=Cup_Holder_Top_Diameter,
  cupHolderHeight=Cup_Holder_Height,
  wallThickness=Wall_Thickness,
  handleSlotCount=Handle_Slot_Count,
  handleSlotHeight=Handle_Slot_Height,
  handleSlotWidth=Handle_Slot_Width,
  handleSlotStartAngle=Handle_Slot_Start_Angle,
  handleSlotEndRefinementType=Handle_Slot_End_Refinement_Type,
  handleSlotEndRefinementSize=Handle_Slot_End_Refinement_Size,
  mountType=Mount_Type,
  baseThickness=Base_Thickness,
  sizeGridToBottomDiameter=Size_Base_Units_To_Bottom_Diameter,
  snapPlacement=Snap_Placement,
  cornerRefinementType=Corner_Refinement_Type,
  cornerRefinementSize=Corner_Refinement_Size,
  liteSnap=(Grid_Type == "Lite"),
  slotSlideDirection=Slot_Slide_Direction,
  slotPosition=Slot_Position,
  slotLockDistribution=Slot_Lock_Distribution,
  slotLockSide=Slot_Lock_Side,
  slotEntryRampFlip=Slot_Entry_Ramp_Flip,
);

module openGridCupholder(
  cupHolderBottomDiameter = 85,
  cupHolderTopDiameter = 90,
  cupHolderHeight = 90,
  wallThickness = 2,
  handleSlotCount = 0,
  handleSlotHeight = 45,
  handleSlotWidth = 30,
  handleSlotStartAngle = 0,
  handleSlotEndRefinementType = "Fillet",
  handleSlotEndRefinementSize = 10,
  mountType = "openConnect",
  baseThickness = 4,
  sizeGridToBottomDiameter = false,
  snapPlacement = "Corners",
  cornerRefinementType = "Fillet",
  cornerRefinementSize = 5,
  liteSnap = false,
  slotSlideDirection = "Up",
  slotPosition = "All",
  slotLockDistribution = "All",
  slotLockSide = "Left",
  slotEntryRampFlip = false,
  anchor,
  orient,
  spin
) {
  $fn = Smoothing;

  outer_bottom_diameter = cupHolderBottomDiameter + 2 * wallThickness;
  outer_top_diameter = cupHolderTopDiameter + 2 * wallThickness;

  sizing_diameter = sizeGridToBottomDiameter ? outer_bottom_diameter : outer_top_diameter;
  units = ceil(sizing_diameter / OG_TILE_SIZE);
  base_size = units * OG_TILE_SIZE;

  openConnectMount = mountType == "openConnect";

  // A slot never reaches past the facade end of the cup.
  slot_height = min(handleSlotHeight, cupHolderHeight);
  // Slot cutters run from the cup axis out to here - past the widest point of
  // the outer surface - so each one removes the full wall thickness at every
  // height, whichever way the body tapers.
  slot_reach = max(outer_bottom_diameter, outer_top_diameter) / 2 + 1;
  // Overhang past the rim, so the cut face is not coplanar with it.
  slot_overhang = 0.01;
  // Clamped so the two ends can never overrun each other or pinch the slot shut.
  slot_end_size = handleSlotEndRefinementType == "None"
    ? 0
    : min(handleSlotEndRefinementSize, handleSlotWidth / 2, slot_height / 2);

  // The one thing both mounts need of the base, so it is not in either branch.
  // How thin is thin enough is a printing question rather than a modelling one,
  // and is left to the user - but zero is not thin, it is absent: the slab
  // vanishes and the cup meets the snaps across a plane of no thickness, which
  // renders without complaint and cannot be printed at all.
  assert(baseThickness > 0,
    str("Base_Thickness must be greater than zero - it is ", baseThickness,
      "mm, which leaves no base for the cup to stand on."));

  // Depth an openConnect slot eats out of the base, from the board-facing face.
  mount_slot_depth = struct_val(ocslot_cfg(), "total_height");

  // Outline of the base, used both to draw it and to keep the slot grid inside
  // it: openconnect_slot_grid() drops any slot whose footprint - the slot plus
  // the wall the library keeps around it - does not fit within this region, so
  // corner refinement can never leave a slot cut open at the edge.
  base_outline = rect([base_size, base_size],
    rounding=(cornerRefinementType == "Fillet" ? cornerRefinementSize : 0),
    chamfer=(cornerRefinementType == "Chamfer" ? cornerRefinementSize : 0));

  // Which slots the grid will actually cut, evaluated the same way the library
  // does, so the echo below can report what the base could not accommodate.
  // The footprint turns with the slide direction, and openconnect_slot_grid()
  // keeps that mapping to itself, so it is repeated here to stay in step.
  slot_footprint = zrot(
    slotSlideDirection == "Left" ? 90
    : slotSlideDirection == "Right" ? -90
    : slotSlideDirection == "Down" ? 180
    : 0,
    struct_val(ocslot_cfg(), "footprint"));
  requested_slots = [
    for (i = [0 : units - 1], j = [0 : units - 1])
      if (is_grid_pos_described(i, j, units, units, slotPosition))
        [-(units - i * 2 - 1) * OG_TILE_SIZE / 2, (units - j * 2 - 1) * OG_TILE_SIZE / 2]
  ];
  fitted_slots = [
    for (cp = requested_slots)
      if (is_pos_shape_in_region(cp=cp, footprint=slot_footprint, limit_region=[base_outline]))
        cp
  ];

  // Everything the openConnect mount needs of the base. These live in the branch
  // rather than carrying a !openConnectMount guard so that a failure reports the
  // condition that actually matters, instead of an implication the reader has to
  // unpick. A statement-position assert only runs when it is reached, so the snap
  // mount never sees them.
  if (openConnectMount) {
    assert(baseThickness >= mount_slot_depth + MIN_BASE_WALL,
      str("Base_Thickness must be at least ", mount_slot_depth + MIN_BASE_WALL,
        "mm for the openConnect mount - ", mount_slot_depth, "mm of openConnect slot plus ",
        MIN_BASE_WALL, "mm of solid floor under it - but it is ", baseThickness,
        "mm. Raise Base_Thickness, or set Mount_Type to Snaps."));

    echo(str(
      "opengrid_cupholder: openConnect mount, ", len(fitted_slots), " slots on a ",
      units, "x", units, " grid over a ", base_size, "x", base_size, "mm base. ",
      "Each slot takes ", mount_slot_depth, "mm of the ", baseThickness,
      "mm base, leaving ", baseThickness - mount_slot_depth, "mm of floor under the cup."
    ));

    if (len(fitted_slots) < len(requested_slots))
      echo(str(
        "opengrid_cupholder: ", len(requested_slots) - len(fitted_slots), " of ",
        len(requested_slots), " slots do not fit inside the base outline and were ",
        "dropped. Reduce Corner_Refinement_Size, or pick a Slot_Position that ",
        "keeps clear of the corners."
      ));

    assert(len(fitted_slots) > 0,
      "No openConnect slot fits inside the base outline, so the holder would have no mount. Reduce Corner_Refinement_Size, or enlarge the cup holder.");
  }

  // Cross-section of one slot cutter, drawn across the slot (X) and along it
  // (Y), with Y = 0 at the rim. Both ends are broken by the same refinement:
  // the closed end takes it as a relief cut into the slot, and the rim end
  // takes it negated, which flares the mouth outward as a lead-in for the
  // handle.
  module slotProfile() {
    // Corner order is [X+Y+, X-Y+, X-Y-, X+Y-]: the two Y+ corners are the
    // closed end of the slot, the two Y- corners are the mouth at the rim.
    // A zero refinement has to be handed over as the scalar 0, not as a list
    // of zeros: BOSL2's rect() module tests `rounding==0` to take its plain
    // square path, and an all-zero LIST fails that test, so it calls the rect()
    // function for a rounded path instead - which ignores _return_override on
    // its own all-zero fast path and hands back a bare path where the module
    // expects [points, override]. The module then reads one point as the whole
    // polygon, and the slot cutter is never drawn.
    ends = slot_end_size == 0
      ? 0
      : [slot_end_size, slot_end_size, -slot_end_size, -slot_end_size];
    fwd(slot_overhang) {
      if (handleSlotEndRefinementType == "Chamfer") {
        rect([handleSlotWidth, slot_height + slot_overhang], chamfer=ends, anchor=FRONT);
      } else {
        rect([handleSlotWidth, slot_height + slot_overhang], rounding=ends, anchor=FRONT);
      }
    }
  }

  // Handle slot cutters, in cupBody's local frame: the cup opening is that
  // frame's TOP face, so the slots are measured down from there and reach down
  // toward the base. That frame is never turned over on the way into the
  // finished model, so zrot() here means what it means in the finished model -
  // the angle is measured looking down into the cup, zero on +X, increasing
  // counterclockwise. Emits nothing when slots are switched off, which leaves
  // the cup body exactly as it would be without this feature.
  module handleSlotCutters() {
    $fn = Smoothing;
    if (handleSlotCount > 0 && slot_height > 0 && handleSlotWidth > 0) {
      for (i = [0 : handleSlotCount - 1]) {
        zrot(handleSlotStartAngle + i * 360 / handleSlotCount)
          up(cupHolderHeight / 2)
            // Swing the profile round so it extrudes radially outward from the
            // cup axis - which keeps the slot sides parallel through the wall -
            // and so the profile's mouth end lands at the rim above and its
            // closed end below.
            rotate([-90, 0, -90])
              linear_extrude(height=slot_reach)
                slotProfile();
      }
    }
  }

  // Hollow tapered cup body, attachable so the mount can position it. Built
  // standing the way it is used: the cup opening is the local TOP and the
  // mounting end the local BOTTOM, so the body's own frame already agrees with
  // the finished model's and neither mount has to turn it over. That is what
  // keeps Handle_Slot_Start_Angle meaning the same thing under both mounts -
  // turning the cup end-for-end would reverse its angular sense, and the two
  // mounts would turn it over about different axes.
  module cupBody(anchor, orient, spin) {
    $fn = Smoothing;
    attachable(
      size=[
        max(outer_bottom_diameter, outer_top_diameter),
        max(outer_bottom_diameter, outer_top_diameter),
        cupHolderHeight,
      ],
      anchor=anchor, orient=orient, spin=spin
    ) {
      difference() {
        cyl(h=cupHolderHeight, d1=outer_bottom_diameter, d2=outer_top_diameter);
        up(0.01) cyl(h=cupHolderHeight + 0.02, d1=cupHolderBottomDiameter, d2=cupHolderTopDiameter);
        handleSlotCutters();
      }
      children();
    }
  }

  // openConnect slots, cut into the board-facing underside of the base - the
  // same face the snaps would stand on. The library builds its grid opening
  // toward its own BOTTOM and extends upward from there, which is already the
  // way round this base needs, so the grid sits on the underside untransformed
  // and eats mount_slot_depth up into the slab. Untransformed also means the
  // library's frame is this base's frame, which is what lets the header state
  // the slide directions as plain +X / +Y axes.
  module mountSlots() {
    down(baseThickness / 2)
      openconnect_slot_grid(
        slot_type="slot",
        horizontal_grids=units,
        vertical_grids=units,
        slot_slide_direction=slotSlideDirection,
        slot_position=slotPosition,
        slot_lock_distribution=slotLockDistribution,
        slot_lock_side=slotLockSide,
        slot_entryramp_flip=slotEntryRampFlip,
        limit_region=[base_outline],
        excess_thickness=EPS
      );
  }

  // openConnect base: the same footprint and corner refinement the snap facade
  // draws, with nothing standing off it, and the slot grid cut into the face
  // that meets the board.
  module openConnectBase(anchor, orient, spin) {
    $fn = Smoothing;
    attachable(size=[base_size, base_size, baseThickness], anchor=anchor, orient=orient, spin=spin) {
      difference() {
        cuboid(
          [base_size, base_size, baseThickness],
          rounding=(cornerRefinementType == "Fillet" ? cornerRefinementSize : 0),
          chamfer=(cornerRefinementType == "Chamfer" ? cornerRefinementSize : 0),
          edges="Z"
        );
        mountSlots();
      }
      children();
    }
  }

  // Render: the base resting on the Z = 0 plane, board-facing side down, with
  // the cup standing on top of it. cupBody already stands the right way up, so
  // both mounts only ever move it - position() places it and nothing rotates
  // it. Do not reach for attach() here: mating the cup to a face by anchor
  // would turn it over to meet that face, and the two mounts present opposite
  // faces, so each would turn it over differently and Handle_Slot_Start_Angle
  // would come out mirrored, and mirrored differently per mount.
  // The 0.1 in each branch is overlap into the base, so the cup and the base
  // share a volume rather than meeting across a face.
  if (openConnectMount) {
    openConnectBase(anchor=BOTTOM)
      position(TOP) down(0.1) cupBody(anchor=BOTTOM);
  } else {
    // The facade draws its snaps on its own TOP, so it is turned over to put
    // them against the board; the cup then stands on what is now its upper
    // face, and the snap tips land on Z = 0 like the openConnect base does.
    // Everything inside that xrot(180) is upside down, the cup included, so
    // the cup gets an xrot(180) of its own to cancel it and stand up again.
    xrot(180) openGridFacade(
      xUnits=units,
      yUnits=units,
      facadeThickness=baseThickness,
      cornerRefinementType=cornerRefinementType,
      cornerRefinementSize=cornerRefinementSize,
      liteSnap=liteSnap,
      includeCornerSnaps=true,
      includeEdgeSnaps=(snapPlacement == "All" || snapPlacement == "Edges"),
      includeInternalSnaps=(snapPlacement == "All"),
      topCornerDirectionalSnaps=false,
      topEdgeDirectionalSnaps=false,
      anchor=TOP
    )
      position(BOTTOM) xrot(180) down(0.1) cupBody(anchor=BOTTOM);
  }
}
