/*
  opengrid_inbox.scad

  A wall-mounted paper / envelope / file inbox that hangs on an openGrid wall
  via openConnect slots cut into its back panel.

  The pocket is a wedge: a full-height back panel against the wall, a shorter
  front panel raked outward so sheets lean back and stay visible, closed at the
  sides by tapering panels, with a finger cutout in the front edge so a stack
  can be grabbed.

  ---------------------------------------------------------------------------
  Licensing

  The pocket geometry in this file is original work by zing3d-labs and is
  licensed under the repository license, CC BY-NC-SA 4.0 (see ../../LICENSE).

  The openConnect mount is generated by mitufy's connector library
  (external/opengrid-projects/lib/openconnect_lib.scad), which is licensed
  Creative Commons Attribution 4.0 International:

      openConnect / openGrid connector libraries
      Created by mitufy - https://github.com/mitufy
      https://www.printables.com/model/1559478-openconnect-opengrids-own-connector-system

  openGrid is created by David D:
      https://www.printables.com/model/1214361-opengrid-walldesk-mounting-framework-and-ecosystem

  This file deliberately depends on the CONNECTOR LIBRARY ONLY. mitufy's
  holder / drawer / shelf / hook / label / gadget generators are CC BY-SA 4.0;
  deriving from one of those would impose ShareAlike terms that conflict with
  this repository's CC BY-NC-SA 4.0 license. Do not reintroduce such a
  dependency here.
  ---------------------------------------------------------------------------
*/

// Brings in BOSL2 (via lib/opengrid_base.scad) along with the openConnect
// slot modules and the OG_/OC_ constants, so no separate BOSL2 include.
include <../../external/opengrid-projects/lib/openconnect_lib.scad>

/* [Paper] */

// Sheet size the pocket is built around. Drives the interior width, and the
// panel heights via the percentages below.
Paper_Size = "US Letter"; // [A4, US Letter, A5, Custom]

// Which way the sheet sits in the pocket. Landscape swaps the two dimensions.
Paper_Orientation = "Portrait"; // [Portrait, Landscape]

// Sheet width in mm, used when Paper_Size is Custom. Give the portrait
// dimensions; Paper_Orientation swaps them.
Custom_Paper_Width = 215.9;

// Sheet height in mm, used when Paper_Size is Custom
Custom_Paper_Height = 279.4;

// Extra interior width beyond the sheet, total across both sides, so sheets
// drop in freely. With Snap_Width_To_Grid on this is only a lower bound - the
// snap rounds up to a whole tile and the surplus becomes clearance. Watch the
// echoed clearance figure: raising this past a tile boundary adds a full 28mm
// of width. The default is 3 because it keeps portrait US Letter on 8 tiles.
Paper_Clearance = 3; // [0:0.5:20]

/* [Pocket Shape] */

// Interior depth of the pocket at the floor - the paper stack capacity, in mm
Pocket_Depth = 50; // [5:1:80]

// Outward rake of the front panel, measured from vertical, in degrees
Rake_Angle = 12; // [0:1:35]

// Height of the back panel, as a percentage of the sheet height. Snapped to
// whole tiles unless Snap_Height_To_Grid is off.
Back_Height_Percent = 80; // [15:1:100]

// Height of the front panel, as a percentage of the sheet height. Must be
// enough below Back_Height_Percent for the side panels to taper.
Front_Height_Percent = 55; // [5:1:95]

/* [Thickness] */

// Thickness of the front and side panels, in mm
Wall_Thickness = 2.4; // [1.2:0.2:6]

// Thickness of the back panel - must be thick enough to contain the openConnect slots
Back_Thickness = 4; // [3.5:0.1:10]

// Thickness of the pocket floor, in mm
Floor_Thickness = 2.4; // [1.2:0.2:6]

/* [Finger Cutout] */

// Shape of the grab cutout in the top edge of the front panel
Finger_Cutout_Style = "Notch"; // [Scallop, Notch, None]

// Width of the cutout, in mm
Finger_Cutout_Width = 70; // [10:1:250]

// How far the cutout reaches down from the front panel top edge, in mm
Finger_Cutout_Depth = 22; // [2:1:100]

/* [Perforation] */

// Pattern cut through the panel faces. None leaves every panel solid.
Perforation_Pattern = "Hex"; // [None, Hex, Square]

// Size of one cell - across the flats for hex, the side length for square - in mm
Perforation_Cell_Size = 12; // [4:0.5:40]

// Material left between neighbouring cells, in mm
Perforation_Wall_Thickness = 2; // [0.8:0.2:8]

// Solid margin kept around every perforated area, in mm. Measured from the
// panel's own edges and from each joint it makes - the floor, the neighbouring
// panels, the finger cutout, and the openConnect slot grid. This is structural,
// not cosmetic: perforating to the edge weakens the panel exactly where the
// mount and the corners take load.
Perforation_Border = 8; // [0:0.5:40]

// Perforate the back panel. Off by default because the back plate carries the
// mount, and with grid snapping on the slot grid covers it edge to edge - there
// is nothing left that is safe to cut away.
Perforate_Back = false;

// Perforate the raked front panel
Perforate_Front = true;

// Perforate the tapering side panels
Perforate_Sides = true;

/* [openConnect Mount] */

// Round the outer width UP to a whole 28mm tile, so the slot grid reaches the
// side edges instead of leaving a partial tile unused. Rounding up rather than
// to nearest keeps the pocket from ever pinching the sheet; the added width
// becomes extra paper clearance.
Snap_Width_To_Grid = true;

// Round the back panel height to the nearest whole 28mm tile, so the slot grid
// reaches the top and bottom edges.
Snap_Height_To_Grid = true;

// Slot columns across the back panel. 0 fits as many as the width allows.
Mount_Horizontal_Grids = 0; // [0:1:20]

// Slot rows up the back panel. 0 fits as many as the height allows.
Mount_Vertical_Grids = 0; // [0:1:20]

// Where the slot grid sits when the back panel is not a whole number of tiles tall
Mount_Vertical_Alignment = "Center"; // [Center, Top, Bottom]

// Which grid positions get a slot
Slot_Position = "All"; // [All, Staggered, Edge Rows, Edge Columns, Corners]

// Which slots get the locking nub. More locks means a tighter fit and a harder install.
Slot_Lock_Distribution = "Corners"; // [All, Staggered, Corners, Top Corners, Bottom Corners, None]

// Side the locking nubs sit on, as seen from the wall side of the back panel
Slot_Lock_Side = "Left"; // [Left, Right]

// Flip the slot entry ramp. Useful when printing the back panel on its side.
Slot_Entry_Ramp_Flip = false;

/* [Misc] */

// Value of $fn for curves on the design
Smoothing = 64; // [16:8:256]

/* [Hidden] */

// Paper presets in mm, [width, height].
A4_SIZE = [210, 297];
US_LETTER_SIZE = [215.9, 279.4];
A5_SIZE = [148, 210];

// Solid material kept behind the deepest point of an openConnect slot.
MIN_BACK_WALL = 0.8;

// How far a perforation cutter is pushed past the panel it cuts, so the hole
// breaks cleanly through both faces instead of leaving a coincident surface.
CUT_OVERSHOOT = 1;

// Presets are stated portrait; Landscape swaps them.
_portraitSize =
  Paper_Size == "A4" ? A4_SIZE
  : Paper_Size == "US Letter" ? US_LETTER_SIZE
  : Paper_Size == "A5" ? A5_SIZE
  : [Custom_Paper_Width, Custom_Paper_Height];

_paperSize = Paper_Orientation == "Landscape"
  ? [_portraitSize.y, _portraitSize.x]
  : _portraitSize;

openGridInbox(
  paperWidth=_paperSize.x,
  paperHeight=_paperSize.y,
  paperClearance=Paper_Clearance,
  pocketDepth=Pocket_Depth,
  rakeAngle=Rake_Angle,
  backHeightPercent=Back_Height_Percent,
  frontHeightPercent=Front_Height_Percent,
  wallThickness=Wall_Thickness,
  backThickness=Back_Thickness,
  floorThickness=Floor_Thickness,
  fingerCutoutStyle=Finger_Cutout_Style,
  fingerCutoutWidth=Finger_Cutout_Width,
  fingerCutoutDepth=Finger_Cutout_Depth,
  perforationPattern=Perforation_Pattern,
  perforationCellSize=Perforation_Cell_Size,
  perforationWallThickness=Perforation_Wall_Thickness,
  perforationBorder=Perforation_Border,
  perforateBack=Perforate_Back,
  perforateFront=Perforate_Front,
  perforateSides=Perforate_Sides,
  snapWidthToGrid=Snap_Width_To_Grid,
  snapHeightToGrid=Snap_Height_To_Grid,
  mountHorizontalGrids=Mount_Horizontal_Grids,
  mountVerticalGrids=Mount_Vertical_Grids,
  mountVerticalAlignment=Mount_Vertical_Alignment,
  slotPosition=Slot_Position,
  slotLockDistribution=Slot_Lock_Distribution,
  slotLockSide=Slot_Lock_Side,
  slotEntryRampFlip=Slot_Entry_Ramp_Flip
);

// Wall-mounted paper inbox, mounted to openGrid by openConnect slots cut into
// the back panel.
//
// Orientation is as-mounted: +Y points at the wall, so the back panel face
// lies in the plane Y = 0 and the pocket hangs out toward -Y. +Z is up.
//
// Panel geometry is kept in one submodule per panel (backPanel, floorPanel,
// frontPanel, sidePanels), and the optional perforation of each face is a
// separate masked pass over the assembled solid rather than something baked
// into the panels. The mount is likewise isolated in mountSlots(), so an
// alternative mounting system can be added alongside it without touching the
// pocket.
module openGridInbox(
  paperWidth = 215.9,
  paperHeight = 279.4,
  paperClearance = 3,
  pocketDepth = 50,
  rakeAngle = 12,
  backHeightPercent = 80,
  frontHeightPercent = 55,
  wallThickness = 2.4,
  backThickness = 4,
  floorThickness = 2.4,
  fingerCutoutStyle = "Notch",
  fingerCutoutWidth = 70,
  fingerCutoutDepth = 22,
  perforationPattern = "Hex",
  perforationCellSize = 12,
  perforationWallThickness = 2,
  perforationBorder = 8,
  perforateBack = false,
  perforateFront = true,
  perforateSides = true,
  snapWidthToGrid = true,
  snapHeightToGrid = true,
  mountHorizontalGrids = 0,
  mountVerticalGrids = 0,
  mountVerticalAlignment = "Center",
  slotPosition = "All",
  slotLockDistribution = "Corners",
  slotLockSide = "Left",
  slotEntryRampFlip = false,
  anchor, orient, spin
) {
  $fn = Smoothing;

  slotHeight = struct_val(ocslot_cfg(), "total_height");

  // Snapping lands the panel on whole tiles so the slot grid reaches its edges
  // with nothing left over. Width rounds UP - rounding down would eat into the
  // paper clearance and could pinch the sheet - so any added width becomes
  // extra clearance. Height rounds to nearest, since nothing constrains it.
  natural_outer_width = paperWidth + paperClearance + 2 * wallThickness;
  outer_width = snapWidthToGrid
    ? OG_TILE_SIZE * max(1, ceil(natural_outer_width / OG_TILE_SIZE))
    : natural_outer_width;
  interior_width = outer_width - 2 * wallThickness;

  natural_back_height = paperHeight * backHeightPercent / 100;
  backHeight = snapHeightToGrid
    ? OG_TILE_SIZE * max(1, round(natural_back_height / OG_TILE_SIZE))
    : natural_back_height;
  frontHeight = paperHeight * frontHeightPercent / 100;

  // Depths are measured forward from the wall plane, and are all positive.
  // The minus sign is applied at the call site, since the model occupies -Y.
  front_slab_run = wallThickness / cos(rakeAngle);
  front_inner_bottom_depth = backThickness + pocketDepth;
  front_outer_bottom_depth = front_inner_bottom_depth + front_slab_run;
  front_inner_top_depth = front_inner_bottom_depth + frontHeight * tan(rakeAngle);
  front_outer_top_depth = front_inner_top_depth + front_slab_run;
  total_depth = front_outer_top_depth;

  assert(backHeight > frontHeight,
    "Back_Height_Percent must exceed Front_Height_Percent, so the side panels can taper.");
  assert(backThickness >= slotHeight + MIN_BACK_WALL,
    str("Back_Thickness must be at least ", slotHeight + MIN_BACK_WALL,
      "mm to contain the openConnect slots plus a solid backing wall."));
  assert(pocketDepth > 2 * wallThickness,
    "Pocket_Depth must leave room for the panel walls; increase it or thin the walls.");
  assert(fingerCutoutStyle == "None" || fingerCutoutWidth < interior_width,
    "Finger_Cutout_Width must be narrower than the pocket interior.");
  assert(fingerCutoutStyle == "None" || fingerCutoutDepth < frontHeight - floorThickness,
    "Finger_Cutout_Depth must not reach the pocket floor.");
  assert(perforationPattern == "None" || perforationCellSize > 0,
    "Perforation_Cell_Size must be greater than zero.");
  assert(perforationPattern == "None" || perforationWallThickness > 0,
    "Perforation_Wall_Thickness must be greater than zero, or the cells would merge into one hole.");
  assert(perforationBorder >= 0,
    "Perforation_Border must not be negative.");

  // Slot grid, sized to whatever whole tiles fit unless overridden.
  h_grids = mountHorizontalGrids > 0 ? mountHorizontalGrids : floor(outer_width / OG_TILE_SIZE);
  v_grids = mountVerticalGrids > 0 ? mountVerticalGrids : floor(backHeight / OG_TILE_SIZE);
  assert(h_grids >= 1 && v_grids >= 1,
    "The back panel is too small for a single openConnect tile (28mm); enlarge the paper size or Back_Height_Percent.");

  echo(str(
    "opengrid_inbox: ", outer_width, " x ", total_depth, " x ", backHeight, "mm outer, ",
    "front panel ", frontHeight, "mm, ",
    h_grids, "x", v_grids, " openConnect tiles leaving ",
    outer_width - h_grids * OG_TILE_SIZE, "mm width and ",
    backHeight - v_grids * OG_TILE_SIZE, "mm height unused by the grid. ",
    "Sheet ", paperWidth, " x ", paperHeight, "mm sits in a ", interior_width,
    "mm pocket (", interior_width - paperWidth, "mm clearance) with ",
    paperHeight - frontHeight, "mm visible above the front panel."
  ));

  grid_height = v_grids * OG_TILE_SIZE;
  grid_center_z =
    mountVerticalAlignment == "Top" ? backHeight - grid_height / 2
    : mountVerticalAlignment == "Bottom" ? grid_height / 2
    : backHeight / 2;

  // Perforation. Every panel's perforatable area is inset by perforationBorder
  // from the panel's own edges AND from each joint it makes, so no hole lands
  // on a corner, on the floor seam, or behind the mount. The horizontal span is
  // the same for the back and front panels: both run the full outer width and
  // both are joined by the side panels along their outer edges.
  perforating = perforationPattern != "None";
  perf_pitch = perforationCellSize + perforationWallThickness;
  perf_width = outer_width - 2 * wallThickness - 2 * perforationBorder;
  perf_z_lo = floorThickness + perforationBorder;

  back_perf_z_hi = backHeight - perforationBorder;
  front_perf_z_hi = frontHeight - perforationBorder;

  // Solid keep-out over the slot grid, so the back panel keeps a continuous
  // backing wall behind every slot. Sizing it from the nominal tile footprint
  // is sound because openconnect_slot_grid() clips its own output to exactly
  // that footprint - no slot, nub or entry ramp can reach outside it - so the
  // border is clearance on top of a hard boundary, not a guess at one.
  grid_keepout_width = h_grids * OG_TILE_SIZE + 2 * perforationBorder;
  grid_keepout_height = grid_height + 2 * perforationBorder;

  // The back panel can only be perforated where something is left outside the
  // keep-out - a strip beside the grid, or a band above or below it.
  back_perf_possible = perf_width > 0 && back_perf_z_hi > perf_z_lo && (
    perf_width > grid_keepout_width
    || back_perf_z_hi > grid_center_z + grid_keepout_height / 2
    || perf_z_lo < grid_center_z - grid_keepout_height / 2
  );

  perf_panels = [
    if (perforateBack) "back",
    if (perforateFront) "front",
    if (perforateSides) "sides"
  ];

  if (perforating)
    echo(str(
      "opengrid_inbox: ", perforationPattern, " perforation, ",
      perforationCellSize, "mm cells on a ", perf_pitch, "mm pitch with a ",
      perforationBorder, "mm solid border, ",
      len(perf_panels) > 0
        ? str("on the ", str_join(perf_panels, ", "), ".")
        : "but no panel is selected, so nothing is cut."
    ));

  if (perforating && perforateBack && !back_perf_possible)
    echo(str(
      "opengrid_inbox: Perforate_Back is on but the ", h_grids, "x", v_grids,
      " slot grid plus its ", perforationBorder,
      "mm border covers the whole back panel, so no holes are cut there. ",
      "Lower Mount_Horizontal_Grids / Mount_Vertical_Grids, or turn off ",
      "Snap_Width_To_Grid / Snap_Height_To_Grid, to open up area outside the grid."
    ));

  // Silhouette of one side panel, seen from the side, as [y, z] pairs.
  side_profile = [
    [0, 0],
    [-front_outer_bottom_depth, 0],
    [-front_outer_top_depth, frontHeight],
    [-backThickness, backHeight],
    [0, backHeight],
  ];

  // Raked front panel, seen from the side, as [y, z] pairs.
  front_profile = [
    [-front_inner_bottom_depth, 0],
    [-front_outer_bottom_depth, 0],
    [-front_outer_top_depth, frontHeight],
    [-front_inner_top_depth, frontHeight],
  ];

  // The part of one side panel that belongs to it alone - the silhouette above
  // with the back plate, the floor slab and the front panel taken out of it.
  // Every edge of this polygon is either a free edge of the panel or a joint
  // with another panel, so insetting the whole thing by perforationBorder is
  // all the masking the side panels need.
  side_inner_profile = [
    [-backThickness, floorThickness],
    [-front_inner_bottom_depth, floorThickness],
    [-front_inner_top_depth, frontHeight],
    [-front_outer_top_depth, frontHeight],
    [-backThickness, backHeight],
  ];

  // Extrudes a [y, z] profile along X, centered on the origin.
  module extrudeProfile(profile, width) {
    rotate([90, 0, 90])
      linear_extrude(height=width, center=true)
        polygon(profile);
  }

  module backPanel() {
    fwd(backThickness / 2) up(backHeight / 2)
      cuboid([outer_width, backThickness, backHeight]);
  }

  module floorPanel() {
    floor_depth = front_outer_bottom_depth - backThickness;
    fwd(backThickness + floor_depth / 2) up(floorThickness / 2)
      cuboid([outer_width, floor_depth, floorThickness]);
  }

  module frontPanel() {
    extrudeProfile(front_profile, outer_width);
  }

  module sidePanels() {
    xcopies(spacing=outer_width - wallThickness, n=2)
      extrudeProfile(side_profile, wallThickness);
  }

  // Grab cutout in the top edge of the front panel. Extruded along Y so the
  // shape reads true from the front despite the rake, and bounded in Y so it
  // never reaches the back panel.
  //
  // `grow` swells the shape by that distance in every in-plane direction,
  // which is how the perforation pass keeps its holes clear of the cutout.
  module fingerCutout(grow = 0) {
    cut_length = total_depth - front_inner_bottom_depth + 2;
    cut_center_depth = front_inner_bottom_depth + cut_length / 2 - 1;

    if (fingerCutoutStyle == "Scallop") {
      // Radius of the circle whose chord is the cutout width at the cutout depth.
      scallop_radius = fingerCutoutDepth / 2 + pow(fingerCutoutWidth, 2) / (8 * fingerCutoutDepth);
      // Growing the radius about the same centre offsets the arc by `grow`.
      fwd(cut_center_depth) up(frontHeight - fingerCutoutDepth + scallop_radius)
        xrot(90) cyl(r=scallop_radius + grow, h=cut_length);
    } else if (fingerCutoutStyle == "Notch") {
      notch_rounding = min(fingerCutoutWidth / 4, fingerCutoutDepth / 2);
      // Anchored at the top, so adding `grow` to the height lowers the floor of
      // the notch by exactly `grow` while its open top stays put.
      fwd(cut_center_depth) up(frontHeight + fingerCutoutDepth)
        cuboid(
          [fingerCutoutWidth + 2 * grow, cut_length, 2 * fingerCutoutDepth + grow],
          rounding=notch_rounding + grow,
          edges=[BOTTOM + LEFT, BOTTOM + RIGHT],
          anchor=TOP
        );
    }
  }

  // A 2D field of cells, filling a spanX by spanY area centred on the origin.
  // Generated in the XY plane so linear_extrude can turn it into a cutter that
  // is then rotated onto whichever panel face is being perforated.
  module patternField(spanX, spanY) {
    if (perforationPattern == "Hex") {
      // Circumradius that puts the flats perforationCellSize apart. Neighbours
      // sit perf_pitch away in all six directions, so every wall between two
      // cells comes out at perforationWallThickness.
      hex_radius = perforationCellSize / sqrt(3);
      column_spacing = perf_pitch * sqrt(3) / 2;
      columns = ceil(spanX / (2 * column_spacing)) + 1;
      rows = ceil(spanY / (2 * perf_pitch)) + 1;
      for (i = [-columns : columns], j = [-rows : rows])
        // Dropping every other column by half a cell is what interlocks the
        // columns into a honeycomb rather than stacking them in line.
        translate([i * column_spacing, j * perf_pitch + (i % 2 == 0 ? 0 : perf_pitch / 2)])
          circle(r=hex_radius, $fn=6);
    } else if (perforationPattern == "Square") {
      columns = ceil(spanX / (2 * perf_pitch)) + 1;
      rows = ceil(spanY / (2 * perf_pitch)) + 1;
      // Corners are rounded rather than square - a sharp internal corner is
      // where a thin panel under load starts to tear.
      for (i = [-columns : columns], j = [-rows : rows])
        translate([i * perf_pitch, j * perf_pitch])
          rect(perforationCellSize, rounding=perforationCellSize / 6);
    }
  }

  // Each panel's cutter is built by masking the cell field in 2D and only then
  // extruding it through the panel. Masking in 3D instead would leave OpenSCAD
  // holding an intersection of hundreds of separate solids: correct, but it
  // overruns the preview normalizer's node budget and F5 renders nothing.
  // Feeding a 2D subtree to linear_extrude collapses it to one polygon first,
  // so each panel contributes a single leaf to the CSG tree.

  // Masking a cell field always slices some cells at a shallow angle, leaving
  // crescents too narrow to print - the slicer turns them into ragged single
  // extrusions or drops them. Opening the field (erode, then dilate by the same
  // amount) deletes every hole narrower than the wall between cells, which is
  // the natural threshold here: no gap in the part ends up thinner than the
  // thinnest gap the pattern already asks for. Cells clear of the mask survive
  // with only their corners rounded to that radius, which prints better anyway.
  module withoutSlivers() {
    offset(r=perforationWallThickness / 2)
      offset(r=-perforationWallThickness / 2)
        children();
  }

  // Back panel. What is left after the side panels, the floor, the top edge and
  // the slot grid have each taken their margin - often nothing at all, which is
  // why Perforate_Back defaults off.
  module backPerforation() {
    perf_height = back_perf_z_hi - perf_z_lo;
    center_z = (perf_z_lo + back_perf_z_hi) / 2;

    if (back_perf_possible)
      fwd(backThickness / 2) up(center_z) xrot(90)
        linear_extrude(height=backThickness + 2 * CUT_OVERSHOOT, center=true)
          withoutSlivers() intersection() {
            difference() {
              rect([perf_width, perf_height]);
              back(grid_center_z - center_z)
                rect([grid_keepout_width, grid_keepout_height]);
            }
            patternField(perf_width, perf_height);
          }
  }

  // Front panel. Masked in the panel's own tilted plane, so the window is a
  // plain rectangle - perf_width across, and the height band measured along the
  // rake rather than vertically. The finger cutout is the one mask that has to
  // come off in 3D, since its cylinder meets the raked face as an ellipse.
  module frontPerforation() {
    perf_height = front_perf_z_hi - perf_z_lo;
    center_z = (perf_z_lo + front_perf_z_hi) / 2;
    face_length = perf_height / cos(rakeAngle);

    if (perf_width > 0 && perf_height > 0)
      difference() {
        // Centred on the middle of the slab and tilted into the rake, so the
        // cells sit square to the panel rather than to the world.
        fwd(front_inner_bottom_depth + center_z * tan(rakeAngle) + front_slab_run / 2)
          up(center_z) xrot(90 + rakeAngle)
            linear_extrude(height=wallThickness + 2 * CUT_OVERSHOOT, center=true)
              withoutSlivers() intersection() {
                rect([perf_width, face_length]);
                patternField(perf_width, face_length);
              }
        fingerCutout(grow=perforationBorder);
      }
  }

  // Side panels. side_inner_profile already excludes every neighbouring panel,
  // so one uniform 2D inset does all the masking.
  module sidePerforation() {
    xcopies(spacing=outer_width - wallThickness, n=2)
      rotate([90, 0, 90])
        linear_extrude(height=wallThickness + 2 * CUT_OVERSHOOT, center=true)
          withoutSlivers() intersection() {
            offset(r=-perforationBorder) polygon(side_inner_profile);
            // The profile lives in -Y and +Z, so the field is shifted off the
            // origin to sit centred on the panel rather than on its corner.
            translate([-total_depth / 2, backHeight / 2])
              patternField(total_depth, backHeight);
          }
  }

  module perforationCuts() {
    if (perforating) {
      if (perforateBack) backPerforation();
      if (perforateFront) frontPerforation();
      if (perforateSides) sidePerforation();
    }
  }

  // openConnect slots, cut into the wall-facing side of the back panel.
  // The library builds a grid in its own frame (+Y up the wall, +Z into the
  // panel), so xrot(90) lands it on the Y = 0 wall plane facing outward.
  module mountSlots() {
    up(grid_center_z) xrot(90)
      openconnect_slot_grid(
        slot_type="slot",
        horizontal_grids=h_grids,
        vertical_grids=v_grids,
        slot_slide_direction="Up",
        slot_position=slotPosition,
        slot_lock_distribution=slotLockDistribution,
        slot_lock_side=slotLockSide,
        slot_entryramp_flip=slotEntryRampFlip,
        excess_thickness=EPS
      );
  }

  named_anchors = [
    named_anchor("wall", [0, total_depth / 2, 0], BACK, 0),
    named_anchor("back_top", [0, total_depth / 2 - backThickness / 2, backHeight / 2], UP, 0),
    named_anchor("pocket_floor",
      [0, total_depth / 2 - (backThickness + pocketDepth / 2), floorThickness - backHeight / 2], UP, 0),
    named_anchor("front_top",
      [0, total_depth / 2 - (front_inner_top_depth + front_slab_run / 2), frontHeight - backHeight / 2], UP, 0),
  ];

  attachable(
    size=[outer_width, total_depth, backHeight],
    anchors=named_anchors,
    anchor=anchor, orient=orient, spin=spin
  ) {
    back(total_depth / 2) down(backHeight / 2)
      difference() {
        union() {
          backPanel();
          floorPanel();
          frontPanel();
          sidePanels();
        }
        fingerCutout();
        perforationCuts();
        mountSlots();
      }
    children();
  }
}
